language: node_js
node_js:
  - lts/*
install:
  - yarn install
script:
  - yarn build
  - sh ./deploy.sh
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vitepress/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main